language: node_js

node_js: 
  - "stable"

cache:
  directories:
    - "node_modules"
    
after_success:
- npm run coveralls

services:
  - postgresql
  
addons:
  postgresql: "9.6"

  before_script:
  - psql -c 'create database epicmail;' -U postgres
  - psql -c "CREATE USER eric WITH PASSWORD '44444';" -U postgres
