sudo: false
language: node_js
node_js:
  - "10.15.1"
branches:
  only:
    - develop
install:
  - npm install
  - npm install -g coveralls
  - npm install -g psql
  - npm install -g codecov
cache:
  directories:
    - "node_modules"
script:
  - npm run test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success:
  - npm run coveralls

services:
  - postgresql
addons:
  postgresql: "9.6"
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


