language: node_js

node_js: 
  - "stable"

cache:
  directories:
    - "node_modules"
    
after_success:
- npm run coveralls

services:
  - postgresql
  
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER eric WITH PASSWORD '44444';" -U postgres
  - cp config/database.yml.travis config/database.yml
test:
  adapter: postgresql
  database: travis_ci_test